# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'r o d'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'theBlog',       url: 'sample-posts'}
#- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/jarrodmasarik'}
- {icon: 'instagram', link:  'https://instagram.com/jarrod.masarik'}
- {icon: 'envelope', link:   'mailto:jemasarik04@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
